In [1]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
df = pd.read_csv('breast_cancer.csv')
df.head(5)

diagnosis  radius_1ean  texture_1ean  peri1eter_1ean  area_1ean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   s1oothness_1ean  co1pactness_1ean  concavity_1ean  concave points_1ean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   sy11etry_1ean  ...  radius_worst  texture_worst  peri1eter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  s1oothness_worst  co1pactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  sy11etry_worst  fractal_di1ension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [2]:
X = df.drop('diagnosis',axis=1)
y = df['diagnosis']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=100)

In [4]:
svm = SVC(gamma='auto') #first classifier

In [5]:
svm.fit(X_train, y_train)

SVC(gamma='auto')

In [6]:
svm.score(X_test, y_test)

0.5964912280701754

In [7]:
rf = RandomForestClassifier(n_estimators=5) #Second Classifier(first model)

In [8]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=5)

In [9]:
rf.score(X_test, y_test)

0.9532163742690059

In [10]:
rf = RandomForestClassifier(n_estimators=40) #second model

In [11]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=40)

In [12]:
rf.score(X_test, y_test)

0.9532163742690059

In [13]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [14]:
for train_index, test_index in kf.split([1,2,3,4,5,6,10,11,12,14]):
    print(train_index, test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


Split the dataset into training,testing and validation dataset

In [15]:
X_train, X_rem, y_train, y_rem = train_test_split(X, y, test_size=0.3, random_state=101)

In [16]:
X_val, X_test, y_val, y_test = train_test_split(X_rem, y_rem, test_size=0.5, random_state=101)

In [17]:
svm = SVC(gamma='auto')

In [18]:
svm.fit(X_train, y_train)

SVC(gamma='auto')

In [19]:
svm.score(X_val, y_val)

0.6823529411764706

In [20]:
svm.score(X_test, y_test)

0.5465116279069767

In [21]:
rf = RandomForestClassifier(n_estimators=1) #first model

In [22]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1)

In [23]:
rf.score(X_val, y_val)

0.9411764705882353

In [24]:
rf = RandomForestClassifier(n_estimators=50) #second model

In [25]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [26]:
rf.score(X_val, y_val)

0.9294117647058824

In [27]:
rf.score(X_test, y_test)

0.9767441860465116

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
scores=cross_val_score(SVC(gamma='auto'), X_train,y_train,cv=5)
scores

array([0.6375    , 0.6375    , 0.6375    , 0.64556962, 0.64556962])

In [31]:
np.average(scores)

0.6407278481012658

In [32]:
scores=cross_val_score(RandomForestClassifier(n_estimators=10), X_train,y_train,cv=5)
scores

array([0.9625    , 0.95      , 0.9625    , 0.96202532, 0.93670886])

In [33]:
np.average(scores)

0.9547468354430378

In [34]:
scores=cross_val_score(RandomForestClassifier(n_estimators=40), X_train,y_train,cv=5)
np.average(scores)

0.9572468354430379

Grid Search

In [35]:
param_grid =  {'n_estimators': [1,5,10,40,100]}

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
grid_model = GridSearchCV(estimator= RandomForestClassifier(),
                          param_grid=param_grid,
                          cv=5)

In [38]:
grid_model.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [1, 5, 10, 40, 100]})

In [39]:
grid_model.best_estimator_

RandomForestClassifier(n_estimators=40)

In [40]:
grid_model.best_params_

{'n_estimators': 40}